### ISSUE TITLE
Getting Error Undefined symbol: ___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by Satish273** [mesibo/messenger-app-ios-swift#1]
I have cloned the project and using git command but facing this issue while running it.
I am using Swift 5 and Xcode 11.3.1

Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      create_tcp_socket(addrinfo*, int, int, int, int) in mesibo(libsom_mesibo_x86_64.o)
      create_tcp_socket(unsigned int, int, int, int, int) in mesibo(libsom_mesibo_x86_64.o)
      do_select(int, unsigned int) in mesibo(libsom_mesibo_x86_64.o)
      do_select_usec(int, unsigned long long) in mesibo(libsom_mesibo_x86_64.o)
      is_socket_closed(int) in mesibo(libsom_mesibo_x86_64.o)
      do_select(int, int, int, unsigned int) in mesibo(libsom_mesibo_x86_64.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mesibo** [comment]
Looks like git was not synced properly. Sync it once again and let us know if the problem persists.

**Comment by Satish273** [comment]
I tried the git sync and also used the LFS command for large file storage but still it is showing the same error message.

**Comment by mesibo** [comment]
Which target are you building for? Also, does the device build works?

**Comment by Satish273** [comment]
Build Target: 10.0
Also, the build is working fine before configuring the Mesibo pods.

**Comment by mesibo** [comment]
do not use pod with demo code.

**Comment by Satish273** [comment]
I'm not using any pod with the demo project.

**Comment by Satish273** [comment]
I just used the below commands:$ mkdir Messenger
$ cd Messenger
$ git lfs install
$ git clone https://github.com/mesibo/messenger-app-ios-swift.git
$ ./fetch_mesibo_webrtc_framework.sh

This command work well in the Xcode 11.4 but not in Xcode 11.3.

**Comment by mesibo** [comment]
We do not see any such issues, code works fine with Xcode 11.4. If you have issues, please file a support ticket,
